### ISSUE TITLE
esp_vfs_fat.h: No such file or directory

### ISSUE THREAD

**Issue by joeyboey** [QuickSpot/walter-esp-idf#2] opened 2024-10-09 20:04 UTC
Hi,

I tried modifying the hello_world example, but failed short after the library inclusion.

| Modul | Version |
| - | - |
| ESP-IDF | v5.3.1 | 
| walter-modem | 1.1.0

The walter-modem package was installed via the integrated component registry in vscode.
Without even changing the example Code, I get the following compiler error:

```cpp
/project/managed_components/dptechnics__walter-modem/src/WalterModem.h:66:10: fatal error: esp_vfs_fat.h: No such file or directory
   66 | #include <esp_vfs_fat.h>
```

I already tried to modify the `CMakeLists.txt` to include the following:

```
idf_component_register(SRCS "main.c"
                    INCLUDE_DIRS "."
                    REQUIRES fatfs vfs)
```

Did I miss something?
Thanks for the help!

**Comment by joeyboey** [comment] 2024-10-10 11:46
Can this be fixed by using a different ESP-IDF Version? I partially managed to fix it, but i just ran into more compiler errors.

**Comment by daanpape** [comment] 2024-10-10 12:41
Hi, @vThibo will help you with this issue.

**Comment by vThibo** [comment] 2024-10-16 09:33
Errors were caused by breaking changes since ESP-IDF v5. A new component version is uploaded which contains the merged PR and fixes the leftover errors.

Thanks for pointing this out, and for the partial fix.

**Closed by vThibo** 2024-10-16 09:33 UTC

**Comment by joeyboey** [comment] 2024-10-23 10:59
@vThibo Thanks a lot, i will look into this.
Thanks for the fix!
